language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: fyT04yY0GSNizVDmTD71IYFoGRgP2FpFRnq6mZOkmyu+Wb3ipodniCPQjDCCV8SjBeyJIvpzzPkBYBFARRTbUEF4zI/KrZ00WYzfAinm78/HvlgBbKy06gEFX5uE90N7J1h6Xl8fL0XWNpvcWLNF3mJ8h08LVDYNcXVak0VYANm9/YtU6InjdQmeX11UmppGw48CNTjJrLldSj0vGwCn5tAVsdbczT1k+frlKeQEG87yQrII5wYyp+aQ2i9IkaibuqUSyhA8H6NZ+kZ0jbD8gKflFFZEebP2tllRtjs+1HqWmvLtkebxT2aox2Ucf/e83qf/qq+e4ute22bKmjLRY5UN8uEUH+O7NpuOVwUa8xpcrhO2Goy5gNaAsDq3+v0Wm0GXJENfMxsc5rpIua7gcfXAqfihl0zkjanLXPWHrJPC1VqWHgR/VcvSLav3Gw9Q7cD+vn7amTyMqvi5pxZQnvhEAKcxMoI55KKE5eF26K+S7pzpdb/J3LMXvkOubklXGtQfjEcICxe1Ug6uBYg7Dw0RDlh85Vr/fUTVttlTShZwTSiYpqFWhDc9u32cvGoaXjFOBQlB1KBehjAd7r1ng+BTg9CltFhM3vxME9VQrNEuS7ufiY/W97BOvq0dSrjFoxEi0DVfOwSfmn6e6gxxs1rl83qgXxU3bBioi6O2DDg=
  app: whispering-coast-36098
  on:
    repo: thinkful-ei17/brent-react-capstone-server
