language: node_js
node_js:
  - "7"
deploy:
  provider: heroku
  api_key:
    secure: B6o5y4DNN6qk4zv3rHANuscI1ulwsIfmJGeGBNMTQhzfFLPuNqrEIeNkTTZahDJHcX15dMNne5/s7BteuWFJYcFjM9XBPqLE/nGZDoLJ/9cNwGtIXntkFClserMuockxey24xjmyDs1c3Gl5JkDzOR4xsgdy66wT/HZcgPKbR65o+IGOv8NHxfmvL6upBAaJkrAOEnAl4bGxnsJkHNN4xsu8VKCeuj12TMTHsIqRrtjWyuKBuiZSFl6TfhODHkZuz+4n1A8Wen5o+j9mdv9/rnWX5Vcil2641/Dmp8AcW0jslegm84rCf33xK6erq2FNRG0Bswlwf0O1+RdwkRU6Q2c/nIBV4u/KN5a/TL0Zj8cY2rIdOjGV2A1BUJCy2OMOfrTzfKqz85sMMkcGMTkrfT1W+Pm7JFGn1baIPUjO4eyEcnHJpuI9SZL1oj9xvJ+2KuTl01AJCalPHzapZt3nbBVCSyZKphYO1Ko9p7GZSSpD2cFm1WKJ6gdQo5NEdEH4i3phwqWloPKXbj64IrOjJQMaefTIlt4lIa/YbOb7DNeHVa5gTt05mgmyjdQWN3I00pNx1gGqOYvz1D0TN1LudUBhI/g8DykXXHtovpOppoJXwP4ynZI9UOYzrAwiEBne3pzyP9A/m7xAeaFwWAGeJjxYkeCw4M/VpdapAlbejqo=
  app: whispering-coast-36098
  on:
    repo: thinkful-ei17/brent-react-capstone-server
